#!/usr/bin/env python3
"""Emit TypeScript registry data from the canonical Python definitions (run from repo root)."""
from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from spl_validator.src.registry import commands as cmd_mod
from spl_validator.src.registry import functions as fn_mod


def main() -> None:
    commands: dict = {}
    for k, v in cmd_mod.COMMANDS.items():
        commands[k] = {
            "name": v.name,
            "type": v.type,
            "required_args": list(v.required_args),
            "optional_args": {kk: vv.__name__ for kk, vv in v.optional_args.items()},
            "clauses": list(v.clauses),
            "limit_key": v.limit_key,
            "semantic_key": v.semantic_key,
            "filters_events": v.filters_events,
        }

    functions: dict = {}
    for k, v in fn_mod.FUNCTIONS.items():
        functions[k] = {
            "name": v.name,
            "min_args": v.min_args,
            "max_args": v.max_args,
            "context": v.context,
            "category": v.category,
            "syntax": v.syntax,
        }

    stats_overrides: dict = {}
    for k, v in fn_mod._STATS_ARITY_OVERRIDES.items():
        stats_overrides[k] = {
            "name": v.name,
            "min_args": v.min_args,
            "max_args": v.max_args,
            "context": v.context,
            "category": v.category,
            "syntax": v.syntax,
        }

    payload = {
        "commands": commands,
        "commandAliases": dict(cmd_mod.COMMAND_ALIASES),
        "generatingCommands": sorted(cmd_mod.GENERATING_COMMANDS),
        "functions": functions,
        "statsArityOverrides": stats_overrides,
        "evalExpressionCommands": sorted(fn_mod.EVAL_EXPRESSION_COMMANDS),
        "statsAggregationCommands": sorted(fn_mod.STATS_AGGREGATION_COMMANDS),
    }

    out_dir = ROOT / "typescript" / "core" / "src" / "generated"
    out_dir.mkdir(parents=True, exist_ok=True)
    json_path = out_dir / "registryData.json"
    json_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    ts_path = out_dir / "registryData.ts"
    ts_path.write_text(
        "// AUTO-GENERATED by typescript/scripts/export_registry.py — do not edit.\n"
        "export default "
        + json.dumps(payload, indent=2, sort_keys=True)
        + " as const;\n",
        encoding="utf-8",
    )
    print(f"Wrote {json_path} and {ts_path}")


if __name__ == "__main__":
    main()
